#!/usr/bin/env bash
set -euo pipefail

# Pick the skills root that actually exists and is non-empty.
# Prefer ~/.agents/skills if it has entries, else fall back to ~/.claude/skills.
root=""
for cand in "$HOME/.agents/skills" "$HOME/.claude/skills"; do
  if [ -d "$cand" ] && [ -n "$(ls -A "$cand" 2>/dev/null)" ]; then
    root="$cand"
    break
  fi
done
if [ -z "$root" ]; then
  echo "scan-skills: WARNING no populated skills root found (checked ~/.agents/skills and ~/.claude/skills)" >&2
  root="$HOME/.agents/skills"
fi

# Resolve the design-engineer memory dir under whichever root exists.
reg="$root/design-engineer/memory/skill-registry.md"
mkdir -p "$(dirname "$reg")"

{
  echo "# Skill Registry (auto-generated by scan-skills.sh)"
  echo "_Refreshed each run. New skills appear here and are eligible for routing._"
  echo
  for d in "$root"/*/; do
    [ -d "$d" ] || continue
    n=$(basename "$d")
    desc=$(awk '/^description:/{sub(/^description:[[:space:]]*/,""); print; exit}' "$d/SKILL.md" 2>/dev/null)
    echo "- **$n** — ${desc:-(no description)}"
  done
} > "$reg"

count=$(grep -c '^- ' "$reg" || true)
if [ "${count:-0}" -eq 0 ]; then
  echo "scan-skills: WARNING wrote 0 skills — check skills root ($root)" >&2
fi
echo "scan-skills: wrote $count skills to registry ($reg)"
